config/routes.rb
RorTutorial::Application.routes.draw do

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  resources :users do
    resources :microposts, :only => :index
  end
  resources :users do
    member do
      get :following, :followers, :reply, :message
    end
  end

  resources :password_reminders, :only => [:new, :create]
  match '/password_reminders/:token', :to=>'password_reminders#edit',  # controller#action
                                     :as=>:edit_password_reminder,     # named route
                                     :via=>'get'                       # HTTP method
  match 'users/:token/password',    :to=>'users#password',  # controller#action
                                    :as=>:password_user,    # named route
                                    :via=>'put'             # HTTP method

  resources :activation_tokens, :only => [:new, :create]

  match 'users/:token/activation',  :to=>'users#activation',  # controller#action
                                    :as=>:activate_user,      # named route
                                    :via=>'get'               # HTTP method

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'

  root :to => 'pages#home'

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                 :integer         not null, primary key
#  name               :string(255)
#  email              :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  encrypted_password :string(255)
#  salt               :string(255)
#  admin              :boolean         default(FALSE)
#  notify_followers   :boolean         default(TRUE)
#  state              :string(255)
#

# MME per a utilitzar les Hash functions
require 'digest'

class User < ActiveRecord::Base

  attr_accessor :password # MME nomes dona acces a la instance var @password que no es guarda a la BBDD

  # MME si es posa, atributs (columnes) als que es podrà accedir via ActiveRecord
  attr_accessible	:name, :email, :password, :password_confirmation, :admin, :notify_followers

  # MME validacions (s'executen just abans de guardar-se a la BBDD si s'invoca save. S'eviten si s'invoca save(false))
  validates :name, :presence => true,
                   :length=> {maximum: 50}

  validates :email, :presence => true,
                    :format => { :with => /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    :uniqueness => { :case_sensitive => false}

  validates :password, :presence => true,
                       :confirmation => true,	# crea un atribut password_confirmation i a la vegada confirma que sigui igual que password
                       :length => { :within => 6..40 }

  # validates :password_confirmation, :presence => true	# MME aixo exigigeix que al crear es passi un :password_confirmation, doncs amb nomes
                  #	  l'anterior validator sol, pot crearse un usuari si no es passa :password_confirmation


  before_save :encrypt_password


  ## MME state_machine per a fer la inscripcio en passos.
  # Atencio, les validacions del model es poden insertar dins la maquina d'estats, perque si son fora, cada cop que es
  # canvia d'estat state_machine utilitza #save i aleshores es comproven totes les validacions, per la qual cosa no
  # canvia d'estat si no se li passen els atributs d'acord a les validacions esperades. Per evitar-ho, es pot redefinir
  # amb :action=> la nova funcio que es crida cada cop que es canvia d'estat, de manera que no es cridin les validacions
  # i/o els callbacks que per defecte fa 
  state_machine :initial => :inactive, :action=>:save_state do
    event :activate do
      transition :inactive => :active
    end
  end

  # MME a l'esborrar un User s'esborren tb els seus Micropost
  has_many :microposts, :dependent => :destroy

  # MME Afegim respostes als usuaris
  has_many :replies, :class_name => 'Micropost',
                     :foreign_key => "in_reply_to",
                     :inverse_of => :replied_user,
                     :dependent => :destroy

  ## User com a seguidor (follower)
  # te molts :relationships apuntant-lo amb la clau follower_id. Si el User s'elimina tots aquests Relationship tambe seran eliminats.
  has_many :relationships, :foreign_key => "follower_id",
                           :dependent => :destroy
  # te molts seguits via :relationships als que s'apunta via :followed_id  (inferit gracies a :followed, que apunta a la vegada als User)
  has_many :following, :through => :relationships,
                       :source => :followed

  ## User com a seguit (followed)
  # te molts :reverse_relationships apuntant-lo amb la clau followed_id. Si el User s'elimina tots aquests Relationship tambe seran eliminats.
  has_many :reverse_relationships, :class_name => "Relationship",
                                   :foreign_key => "followed_id",
                                   :dependent => :destroy
  # te molts seguidors via :reverse_relationships als que s'apunta via :follower_id  (inferit gracies a :follower, que apunta a la vegada als User)
  has_many :followers, :through => :reverse_relationships

  # Torna els microposts dels usuaris seguits per un user, per exemple:
  #    usr=User.find(12)
  #    usr.following_microposts
  # (no el faig anar finalment: Micropost.from_users_followed_by(user) ho he implementat sense aquests metode perque
  # em falten els microposts del propi user) 
  has_many :following_microposts, :through => :following, 
                                  :source => :microposts

  # Si n'hi ha, te un password_reminder
  has_one :password_reminder

  # Si n'hi ha, te un activation_token
  has_one :activation_token

  # Torna l'User de l'email si el password es correcte
  def self.authenticate(email, submited_pwd)
    if usr = find_by_email(email)
      usr.has_password?(submited_pwd) ? usr : nil
    else
      nil
    end
  end

  # Torna l'User del id si el salt es correcte (s'utilitza per les sessions)
  def self.authenticate_with_salt(id, salt)
    user = find_by_id(id)
    (user && user.salt == salt) ? user : nil
  end

  # verifica si el password correspon a l'User
  def has_password?(submited_pwd)
    self.encrypted_password == encrypt(submited_pwd)
  end

  def feed
    #Micropost.from_users_followed_by self
    # Microposts from
    #   self
    #   self.following
    #   self.replies
    Micropost.not_messages.from_users_followed_by_or_in_reply_to self
  end

  # Is usr being followed by self?
  def following? usr
    following.include? usr
    # MME segons el tutorial seria
    #relationships.find_by_followed_id(followed)
  end

  def follow! usr
    relationships.create! :followed_id => usr.id
  end

  def unfollow! usr
    relationships.find_by_followed_id(usr.id).destroy if following?(usr)
  end

  def replies_to(usr, content)
    microposts.create :content=>content, :in_reply_to=>usr.id, :private=>false
  end

  def sends_to(usr, content)
    microposts.create :content=>content, :in_reply_to=>usr.id, :private=>true
  end

  def messages_to usr
    microposts.messages.where(:in_reply_to => usr.id)
  end

  def messages_from usr
    usr.microposts.messages.where(:in_reply_to => self.id)
  end

  def messages_to_or_from usr
    Micropost.messages.between usr, self
  end
  alias conversation_with messages_to_or_from

  # MME generates a unique login name for a user
  def pseudo_login_name
    name.downcase.split.join("_")+"_"+ id.to_s
  end

  # MME generate, remove and find_by password_reminders and activation_tokens
  # MME creates a password reminder if it doesn't yet exist
  def generate_password_reminder
    create_password_reminder!(:token=>SecureRandom.hex(32)) unless password_reminder
  end

  # MME removes if exists
  def remove_password_reminder
    password_reminder.delete if password_reminder
  end

  # finds a user from a token
  def self.find_by_password_reminder(token)
    pr=PasswordReminder.find_by_token(token, :include=>:user)
    pr.user if pr
  end

  def generate_activation_token
    create_activation_token!(:token=>SecureRandom.hex(32)) unless activation_token
  end

  def remove_activation_token
    activation_token.delete if activation_token
  end

  def self.find_by_activation_token(token)
    at=ActivationToken.find_by_token(token, :include=>:user)
    at.user if at
  end

  # MME finds a user from a pseudo_login_name
  # first tries to get it from an id
  # last tries to get it from a name
  def self.find_by_pseudo_login_name(pln)
    nam=pln.split("_")
    id = nam.last.to_i
    if id>0 # First attempt: if it exists an id as the last part off the pln 
      User.find_by_id(id)
    else # Second attempt: try to generate a name from a pln
      User.find_by_name(nam.map(&:capitalize).join(" "))
    end
  end

  # FUNCIONS PRIVADES
  private

    def encrypt_password
      self.salt = make_salt unless has_password?(password)	# self.salt resets everytime user changes its password
      self.encrypted_password = encrypt(password)	# password refers to self.password
    end

    def make_salt
      Digest::SHA2.hexdigest "#{Time.now.utc}--#{password}"
    end

    def encrypt(str)
      Digest::SHA2.hexdigest "#{salt}--#{str}"
    end

    # salva nomes la columna state (evitant callbacks i validations)
    def save_state
      update_column 'state', state
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # MME Els usuaris no autenticats nomes poden mostrar un usuari i crear una compta
  before_filter :authenticate, :except => [:show, :new, :create, :password, :activation]
  # MME evitem que usuaris no correctes puguin editar altres registres
  before_filter :correct_user, :only => [:edit, :update]
  # MME nomes permetem esborrar als administradors
  before_filter :admin_user, :only => :destroy
  # MME Signed-in users have no reason to access the new and create actions
  before_filter :signed_in_user, :only => [:new, :create]

  # MME will_paginate: valor per defecte de items per pagina
  ITEMS_PER_PAGE = 5

  # GET /users
  # GET /users.json
  def index
    @title = "All users"
    @users = User.paginate(:page=>params[:page], :per_page => ITEMS_PER_PAGE)
    session[:idx_last_page]=params[:page]

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.not_messages.paginate(:page=>params[:page], :per_page => 5)
    @title = "Show '#{@user.name}'"

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @title = "Sign Up"
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    # @user ja el troba el before_filter correct_user
    # @user = User.find(params[:id]) 
    @title = "Edit User"
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    respond_to do |format|
      if @user.save
        format.html {
          @user.generate_activation_token
          UserMailer.activation_token(@user).deliver
          flash[:success] = "Benvingut a Rettiwet! ... T'hem enviat un mail per activar el teu account ... consulta'l en breu!"
          redirect_to signin_path
        }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { 
          @title = "Sign Up"
          render action: "new" 
        }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    # @user ja el troba el before_filter correct_user
    # @user = User.find(params[:id]) 

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, :flash => { success: 'Profile updated.'} }
        format.json { head :ok }
      else
        format.html { 
          @title = "Edit user"
          render "edit" 
        }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # Actualitza el password de l'usuari, pero sense ser necessari que l'usuari estigui signed in (password reminder)
  # PUT /users/1/password
  # PUT /users/1.json/password
  def password
    @user = User.find_by_password_reminder(params[:token])
    respond_to do |format|
      if @user
        if @user.update_attributes(params[:user])
          format.html { redirect_to root_path, :flash => { success: 'Password updated'} }
          format.json { head :ok }
        else
          format.html {
            @title = "Edit user"
            render "password_reminders/edit"
          }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      else
        format.html { redirect_to root_path, :flash => { error: 'Invalid Password Reminder'} }
        format.json { head :ok }
      end
    end
  end

  # Activa l'usuari quan aquest clica al link del token que se li ha enviat
  # GET /users/1/activation
  # GET /users/1.json/activation
  def activation
    @user = User.find_by_activation_token(params[:token])
    respond_to do |format|
      if @user
        @user.activate
        @user.remove_activation_token
        format.html { redirect_to signin_path, :flash => { success: "You've successfully activated your account ... please signin!"} }
        format.json { head :ok }
      else
        format.html { redirect_to root_path, alert: 'Invalid Activation Token' }
        format.json { head :ok }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    user=User.find(params[:id])
    if current_user?(user)
      flash[:error] = "Admin user can't do suicide"
    else
      user.destroy
      flash[:success] = "User destroyed"
    end
    
    respond_to do |format|
      format.html { redirect_to users_url(:page=>session[:idx_last_page]) }
      format.json { head :ok }
    end

  end

  # GET /users/1/following
  # GET /users/1/following.json
  def following
    @title = "Following"
    @user=User.find(params[:id])
    @other_users=@user.following.paginate(:page=>params[:page], :per_page => 30)
    respond_to do |format|
      format.html { render 'show_follow' }
      format.json { render json: @other_users }
    end
  end

  # GET /users/1/followers
  # GET /users/1/followers.json
  def followers
    @title = "Followers"
    @user=User.find(params[:id])
    @other_users=@user.followers.paginate(:page=>params[:page], :per_page => 30)
    respond_to do |format|
      format.html { render 'show_follow' }
      format.json { render json: @other_users }
    end
  end

  # Prepara el formulari de resposta per a enviar un micropost reply a un usuari
  # GET /users/1/reply
  # GET /users/1/reply.json
  def reply
    @title = "Reply"
    @user=User.find(params[:id])
    @micropost=Micropost.new
    respond_to do |format|
      format.html
      format.json { render json: @micropost }
    end

  end

  # Prepara el formulari de resposta per a enviar un micropost message a un usuari
  # GET /users/1/message
  # GET /users/1/message.json
  def message
    @title = "Message"
    @user=User.find(params[:id])
    @messages = current_user.messages_to_or_from(@user).paginate(:page=>params[:page], :per_page => 10)
    @message=Micropost.new
    respond_to do |format|
      format.html
      format.json { render json: @messages }
    end
  end

  private

    def correct_user
      @user ||= User.find(params[:id])
      unless current_user?(@user)
        flash[:notice]="No es permes editar #{@user.name} per #{current_user.name}"
        redirect_to root_path
      end
    end

    def admin_user
      unless current_user && current_user.admin?
        flash[:notice]="Nomes poden esborrar els usuaris admin"
        redirect_to root_path
      end
    end

    def signed_in_user
      if signed_in?
        flash[:notice]="#{current_user.name} ... you've already Signed Up!"
        redirect_to root_path
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper

  # MME torna un gravatar o, en el seu defcte, un avatar local aleatori
  def gravatar_for(user, options = {})
   	options ||={}
    default_img_url=root_url+url_for("assets/avatars/#{random_avatar}")
   	opts = { :default => default_img_url , :size => 50 }
    opts.merge! options
    options = {
    	:alt => h(user.name),
    	:class => 'gravatar round',
    	:gravatar => opts
    }
  	# if gravatar doesn't exist we have to resize random_avatar
    options.merge!({:heigth=>opts[:size], :width=>opts[:size]}) if opts.has_key? :size
    gravatar_image_tag user.email.downcase, options
  end

  # MME returns a link with a shortened version of the name to include in replies
  def shortened_link_for(user)
    #link_to "@" + user.email.match(/(.*)@/i)[1] + user.id.to_s, user
    link_to "@" + user.pseudo_login_name, user
  end

  private

    # chooses a random image (png, jpg or gif) from .../avatars directory
    def random_avatar
      avatars_dir = File.join(Rails.configuration.root.to_s,"/app/assets/images/avatars/")
      Dir["#{avatars_dir}*{png,jpg,gif}"].map {|f| f.sub!(avatars_dir,"")}.sample
    end

end

app/views/users/_follow.html.erb
<!-- Crea un boto a partir d'un formulari amb un nou Relationship "efimer" i l'unic camp accessible preomplert i amagat -->

<!-- Vesio AJAX -->
<%= form_for current_user.relationships.build(:followed_id => @user.id), :remote => true do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <div class="actions"><%= f.submit "Follow" %></div>
<% end %>

<!-- Versio normal -->
<%
=begin %>
<%= form_for current_user.relationships.build(:followed_id => @user.id) do |f| %>
  <!-- el camp amagat correspont a l'atribut hidden_field (l'unic accessible de Relationship) -->
  <div><%= f.hidden_field :followed_id %></div>
  <div class="actions"><%= f.submit "Follow" %></div>
<% end %>
<%
=end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <%= render :partial => 'shared/error_messages', :object => @user.errors %>
  <% end %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :admin, "Administrator?" %><br />
    <%= f.check_box :admin%>
  </div>
   <div class="field">
    <%= f.label :notify_followers, "Send mail when followers added / deleted?" %><br />
    <%= f.check_box :notify_followers%>
  </div>
  <div class="actions">
    <%= f.submit (controller.action_name=="new" ? "Sign Up!" : "Update!") %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<!-- Crea un boto a partir d'un formulari amb un nou Relationship "efimer" del qual nomes utilitza el seu id al fer el request -->

<!-- Vesio AJAX -->
<%= form_for current_user.relationships.find_by_followed_id(@user), :html => { :method => :delete },  :remote => true do |f| %>
  <div class="actions"><%= f.submit "Unfollow" %></div>
<% end %>

<!-- Versio normal -->
<%
=begin %>
<%= form_for current_user.relationships.find_by_followed_id(@user), :html => { :method => :delete } do |f| %>
  <div class="actions"><%= f.submit "Unfollow" %></div>
<% end %>
<%
=end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, :size => 25 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? %>
     | 
    <%= link_to 'Delete', user, 
        method: :delete,
        confirm: 'Are you sure?', 
        title: "Delete #{user.name}"  # tootltip
    %>
  <% end %>
</li>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<table class="profile" summary="Profile information">
  <tr>
    <td class="main">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
        <p><a href="http://gravatar.com/emails" class="petit_link" target="_blank">canvia avatar</a></p>
      </h1>
    </td>
    <td class="sidebar round">
      <%= render 'form' %>
    </td>
  </tr>
</table>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/message.html.erb
<table class="front" summary="For signed-in users">
  <tr>
    <td class="main">
      <h1 class="micropost">Message to <%= @user.name %></h1>
      <!-- MME Si es passen varis arguments a render, els partial dona problemes si no es posa :partial=>'partial'  -->
      <%= render :partial=>'shared/micropost_form', :locals => { :micropost => @message, :receiver => @user, :private => true } %>
      <% unless @messages.empty? %>
        <table class="microposts" summary="User messages">
          <%= render :partial=>'shared/message_item', :collection=>@messages %>
        </table>
        <%= will_paginate @messages %>
      <% end %>
    </td>
    <td class="sidebar round">
      <%= render :partial=>'shared/user_info', :object => current_user %>
    </td>
  </tr>
</table>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/reply.html.erb
<table class="front" summary="For signed-in users">
  <tr>
    <td class="main">
      <h1 class="micropost">In reply to <%= @user.name %></h1>
      <!-- MME Si es passen varis arguments a render, els partial dona problemes si no es posa :partial=>'partial'  -->
      <%= render :partial=>'shared/micropost_form', :locals => { :micropost => @micropost, :receiver => @user, :private => false } %>
    </td>
    <td class="sidebar round">
      <%= render :partial=>'shared/user_info', :object => current_user %>
    </td>
  </tr>
</table>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<table class="profile" summary="Profile information">
  <tr>
    <td class="main">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
      <% if signed_in? %>
        <table>
          <tr>
            <td><%= render 'follow_form' %></td>
            <td><%= button_to 'Reply', reply_user_path(@user), :method => :get %></td>
            <td><%= button_to 'Message', message_user_path(@user), :method => :get %></td>
          </tr>
        </table>
      <% end %>
      <% unless @microposts.empty? %>
        <table class="microposts" summary="User microposts">
          <%= render @microposts %>
        </table>
        <%= will_paginate @microposts %>
      <% end %>
    </td>
    <td class="sidebar round">
      <strong>Name</strong> <%= @user.name %><br />
      <strong>Email</strong> <%= @user.email %><br />
      <strong>URL</strong>  <%= link_to user_path(@user) %><br />
      <strong>Microposts</strong> <%= @user.microposts.count %>
      <%= render :partial => 'shared/stats', :object => @user %>
    </td>
  </tr>
</table>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/show_follow.html.erb
<p id="notice"><%= notice %></p>

<table summary="Information about following/followers">
  <tr>
    <td class="main">
      <h1><%= @title %></h1>

      <% unless @other_users.empty? %>
        <ul class="users">
          <%= render @other_users %>
        </ul>
        <%= will_paginate @other_users %>
      <% end %>
    </td>
    <td class="sidebar round">
      <strong>Name</strong> <%= @user.name %><br />
      <strong>URL</strong> <%= link_to user_path(@user), @user %><br />
      <strong>Microposts</strong> <%= @user.microposts.count %>
      <%= render :partial => 'shared/stats', :object => @user %>
      <% unless @other_users.empty? %>
        <% @other_users.each do |user| %>
          <%= link_to gravatar_for(user, :size => 30), user, :title=>user.name %>
        <% end %>
      <% end %>
    </td>
  </tr>
</table>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>