config/routes.rb
RorTutorial::Application.routes.draw do

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  resources :users do
    resources :microposts, :only => :index
  end
  resources :users do
    member do
      get :following, :followers, :reply, :message
    end
  end

  resources :password_reminders, :only => [:new, :create]
  match '/password_reminders/:token', :to=>'password_reminders#edit',  # controller#action
                                     :as=>:edit_password_reminder,     # named route
                                     :via=>'get'                       # HTTP method
  match 'users/:token/password',    :to=>'users#password',  # controller#action
                                    :as=>:password_user,    # named route
                                    :via=>'put'             # HTTP method

  resources :activation_tokens, :only => [:new, :create]

  match 'users/:token/activation',  :to=>'users#activation',  # controller#action
                                    :as=>:activate_user,      # named route
                                    :via=>'get'               # HTTP method

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'

  root :to => 'pages#home'

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

end

app/views/shared/_error_messages.html.erb
<div id="error_explanation" class="error">
  <h2><%= pluralize(error_messages.count, "error") %> 
      prohibited this user from being saved:</h2>
  <p>There were problems with the following fields:</p>
  <ul>
  <% error_messages.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>

app/views/shared/_feed.html.erb
<% if @feed_items && @feed_items.any? %>
  <table class="microposts" summary="User microposts">
    <%= render :partial => 'shared/feed_item', :collection => @feed_items %>
  </table>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<tr>
  <td class="gravatar">
    <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  </td>
  <td class="micropost">
    <span class="user">
      <%= link_to feed_item.user.name, feed_item.user %>
    </span> <br />
    <span class="content">
      <% replier = feed_item.is_reply? ? (shortened_link_for(feed_item.replied_user)+" ") : "" %>
<%
=begin %>
      <% replier = feed_item.is_reply? ? (feed_item.in_reply_to.to_s + " ") : "" %>
<%
=end %>
      <% txt = feed_item.content %>
      <%= replier + wrap_words(txt) %>
    </span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
    </span>
  </td>
  <% if current_user?(feed_item.user) %>
  <td>
    <%= link_to "delete", feed_item, :method => :delete,
                                     :confirm => "You sure?",
                                     :title => feed_item.content %>
  </td>
  <% end %>
</tr>

app/views/shared/_message_item.html.erb
<tr>
  <td class="gravatar">
    <%= link_to gravatar_for(message_item.user), message_item.user %>
  </td>
  <td class="micropost">
    <span class="user">
      <%= link_to message_item.user.name, message_item.user %>
    </span> <br />
    <span class="content">
      <% replier = message_item.is_reply? ? (shortened_link_for(message_item.replied_user)+" ") : "" %>
<%
=begin %>
      <% replier = message_item.is_reply? ? (message_item.in_reply_to.to_s + " ") : "" %>
<%
=end %>
      <% txt = message_item.content %>
      <%= replier + wrap_words(txt) %>
    </span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(message_item.created_at) %> ago.
    </span>
  </td>
  <% if current_user?(message_item.user) %>
  <td>
    <%= link_to "delete", message_item, :method => :delete,
                                     :confirm => "You sure?",
                                     :title => message_item.content %>
  </td>
  <% end %>
</tr>

app/views/shared/_micropost_form.html.erb
<%= form_for(micropost) do |f| %>
  <% if micropost.errors.any? %>
    <%= render :partial=>'shared/error_messages', :object => micropost.errors %>
  <% end %>
  <% if receiver %>
    <%= f.hidden_field :in_reply_to, { :value => receiver.id } %>
    <%= f.hidden_field :private, { :value => private } %>
  <% end %>
  <div class="field">
    <%= f.text_area :content, :onkeyup=>'charsleft(this)'  %>
  </div>
  <div class="small quiet">
    if content begins with <span class="loud">@pln</span> you'll send a repy 
    <br />
    if content begins with <span class="loud">*pln</span> you'll send a message (private)  
    <br />
    where <span class="loud">pln</span> is the pseudo_login_name, i.e. the downcased name and/or the id separated by underscores
  </div>
  <div class="actions">
    <%= f.submit "Submit"%>
  </div>
  <!-- S'actualitza amb el numero de caracters escrits -->
  <div id="charNum">0</div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <table summary="User stats">
    <tr>
      <td>
        <a href="<%= following_user_path(stats) %>">
          <span id="following" class="stat">
            <%= stats.following.count %> following
          </span>
        </a>
      </td>
      <td>
        <a href="<%= followers_user_path(stats) %>">
          <span id="followers" class="stat">
            <%= pluralize(stats.followers.count, "follower") %>
          </span>
        </a>
      </td>
    </tr>
  </table>
</div>

app/views/shared/_user_info.html.erb
    <div class="user_info">
      <a href="<%= user_path(user_info) %>">
        <%= gravatar_for user_info, :size => 30 %>
        <span class="user_name">
          <%= user_info.name %>
        </span>
      </a>
      <span class="microposts">
        <%= pluralize(user_info.microposts.count, "micropost") %>
      </span><br />
      <%= render :partial => "shared/stats", :object => user_info %>
    </div>