config/routes.rb
RorTutorial::Application.routes.draw do

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  resources :users do
    resources :microposts, :only => :index
  end
  resources :users do
    member do
      get :following, :followers, :reply, :message
    end
  end

  resources :password_reminders, :only => [:new, :create]
  match '/password_reminders/:token', :to=>'password_reminders#edit',  # controller#action
                                     :as=>:edit_password_reminder,     # named route
                                     :via=>'get'                       # HTTP method
  match 'users/:token/password',    :to=>'users#password',  # controller#action
                                    :as=>:password_user,    # named route
                                    :via=>'put'             # HTTP method

  resources :activation_tokens, :only => [:new, :create]

  match 'users/:token/activation',  :to=>'users#activation',  # controller#action
                                    :as=>:activate_user,      # named route
                                    :via=>'get'               # HTTP method

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'

  root :to => 'pages#home'

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

end

app/models/password_reminder.rb
# == Schema Information
#
# Table name: password_reminders
#
#  id      :integer         not null, primary key
#  user_id :integer
#  token   :string(255)
#

class PasswordReminder < ActiveRecord::Base

  attr_accessible :token

  belongs_to :user

end

app/controllers/password_reminders_controller.rb
class PasswordRemindersController < ApplicationController

  # Presenta el formulari pera omplir el mail on enviar el activation token
  # GET /password_reminders/new
  def new
    @title = "Generate Password Reminder"
  end

  # Envia el password_reminder (si no existeix el crea))
  # POST /password_reminders
  def create
    user = User.find_by_email(params[:password_reminder][:email])
    if user.nil?
      # Create an error message and re-render the password reminder form
      flash.now[:error] = "User doesn't exist!"
      @title = "Recreate Password"
      render 'new'
    else
      # Generates a Password Reminder and notifies user that is being sent a mail
      user.generate_password_reminder
      UserMailer.password_reminder(user).deliver
      flash[:success] = "Password Reminder sent to #{user.email}! check it soon."
      redirect_to root_path
    end
  end

  # Mostra el formulari per recrear el password
  # GET /password_reminders/:token
  def edit
    pr = PasswordReminder.find_by_token(params[:token], :include=>:user)  # inclou el user
    unless pr.nil?
      @user = pr.user
      @title = "Type new password"
    else
      flash[:error] = "Password Reminder is not valid"
      redirect_to root_path
    end
  end

end

app/views/password_reminders/edit.html.erb
<h1>Regenerate Password</h1>

<table class="profile" summary="Profile information">
  <tr>
    <td class="main">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </td>
    <td class="sidebar round">
      <%= form_for(@user, :url=>password_user_path(@user.password_reminder.token)) do |f| %>
        <% if @user.errors.any? %>
          <%= render :partial => 'shared/error_messages', :object => @user.errors %>
        <% end %>
        <%= f.hidden_field :name %>
        <%= f.hidden_field :email %>
        <%= f.hidden_field :admin%>
        <%= f.hidden_field :notify_followers%>
        <div class="field">
           <%= f.label :password %><br />
           <%= f.password_field :password %>
        </div>
        <div class="field">
          <%= f.label :password_confirmation, "Confirmation" %><br />
          <%= f.password_field :password_confirmation %>
        </div>
        <div class="actions">
          <%= f.submit "Set Password!" %>
        </div>
      <% end %>
    </td>
  </tr>
</table>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/password_reminders/new.html.erb
<h1>Retrieve password</h1>

<%= form_for :password_reminder, :url => password_reminders_path do |f| %>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit "Send!" %>
  </div>
<% end %>

<p>New user? <%= link_to "Sign up now!", signup_path %></p>