config/routes.rb
RorTutorial::Application.routes.draw do

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  resources :users do
    resources :microposts, :only => :index
  end
  resources :users do
    member do
      get :following, :followers, :reply, :message
    end
  end

  resources :password_reminders, :only => [:new, :create]
  match '/password_reminders/:token', :to=>'password_reminders#edit',  # controller#action
                                     :as=>:edit_password_reminder,     # named route
                                     :via=>'get'                       # HTTP method
  match 'users/:token/password',    :to=>'users#password',  # controller#action
                                    :as=>:password_user,    # named route
                                    :via=>'put'             # HTTP method

  resources :activation_tokens, :only => [:new, :create]

  match 'users/:token/activation',  :to=>'users#activation',  # controller#action
                                    :as=>:activate_user,      # named route
                                    :via=>'get'               # HTTP method

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'

  root :to => 'pages#home'

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

end

app/views/layouts/_debug_info.html.erb
<br />
<div class = "notice round prepend-1">
  <div class='info'>
  	<%= print_debug_expressions "current_user.inspect", "cookies.inspect" %>
  </div>
  <h6>Params</h6>
  <span class="small">params hash is used to pass objects from view to controller</span>
  <%= debug(params) %>
  <h6>Session</h6>
  <span class="small">session hash is used to pass around objects between server and client</span>
  <%= debug(session) %>
  <h6>Assigns</h6>
  <span class="small">assigns hash is used to pass instance vars from controller to views</span>
  <%= debug(assigns) %>
</div>  

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
      <li><a href="http://www.railstutorial.org/">Rails Tutorial</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <table>
    <tr>
      <td>
        <%= link_to logo, root_path %>
      </td>
      <td>
          <nav class="round">
            <ul>
              <li><%= link_to "Home", root_path %></li>
              <% if signed_in? %>
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Users", users_path %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <% end %>
              <li><%= link_to "Help", help_path %></li>
              <li>
                <% unless signed_in? %>
                  <%= link_to "Sign in", signin_path %>
                <% else %>
                  <%= link_to "Sign out", signout_path, :method=>:delete %>
                <% end %>
              </li>
            </ul>
          </nav>
      </td>
    </tr>
  </table>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->  
<%= stylesheet_link_tag "blueprint/screen", :media => 'screen' %>
<%= stylesheet_link_tag "blueprint/print", :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <!-- MME el js es necessari per a que funcionin les confirmacions al esborrar per exemple -->
    <%= javascript_include_tag "application" %>
    <!-- MME es l'icon que surt a la barra de direccio -->
    <%= auto_discovery_link_tag :rss %>
    <%= auto_discovery_link_tag :atom %>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      
      <section class="round">
        <% if flash.any? %>
          <% flash.each do |key, value| %>
            <div class="flash <%= key %>"><%= value %></div>
          <% end %>
        <% end %>
        <%= yield %>
      </section>

      <%= render 'layouts/footer' %>
      <% if Rails.env.development? %>
        <%= render 'layouts/debug_info' %>
      <% end %>
    </div>  
    <!-- Exemple de script: llegeix les cookies -->
    <p>
    <strong> Mostra les teves cookies </strong>
    <script>document.write(document.cookie);</script>
    </p>
  </body>
</html>